//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVModExplorer.Locales {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVModExplorer.Locales.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compress ähnelt.
        /// </summary>
        public static string Context_Menu_Compress {
            get {
                return ResourceManager.GetString("Context_Menu_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Context_Menu_Delete {
            get {
                return ResourceManager.GetString("Context_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download All ähnelt.
        /// </summary>
        public static string Context_Menu_Download {
            get {
                return ResourceManager.GetString("Context_Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upgrade mod to DT ähnelt.
        /// </summary>
        public static string Context_Menu_DT_Upgrade {
            get {
                return ResourceManager.GetString("Context_Menu_DT_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Metadata ähnelt.
        /// </summary>
        public static string Context_Menu_EditMeta {
            get {
                return ResourceManager.GetString("Context_Menu_EditMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install Mod ähnelt.
        /// </summary>
        public static string Context_Menu_InstallMod {
            get {
                return ResourceManager.GetString("Context_Menu_InstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Info ähnelt.
        /// </summary>
        public static string Context_Menu_Scrape {
            get {
                return ResourceManager.GetString("Context_Menu_Scrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Info &amp; Compress ähnelt.
        /// </summary>
        public static string Context_Menu_Scrape_Compress {
            get {
                return ResourceManager.GetString("Context_Menu_Scrape_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive ähnelt.
        /// </summary>
        public static string Menu_Download_Archive {
            get {
                return ResourceManager.GetString("Menu_Download_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upgrade for DT ähnelt.
        /// </summary>
        public static string Menu_Download_DTUpgrade {
            get {
                return ResourceManager.GetString("Menu_Download_DTUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Directory ähnelt.
        /// </summary>
        public static string Menu_Download_Remove {
            get {
                return ResourceManager.GetString("Menu_Download_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collect Data from Url ähnelt.
        /// </summary>
        public static string Menu_File_Collect {
            get {
                return ResourceManager.GetString("Menu_File_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To Archive ähnelt.
        /// </summary>
        public static string Menu_File_To_Archive {
            get {
                return ResourceManager.GetString("Menu_File_To_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Penumbra ähnelt.
        /// </summary>
        public static string Menu_Penumbra {
            get {
                return ResourceManager.GetString("Menu_Penumbra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Mod ähnelt.
        /// </summary>
        public static string Menu_Penumbra_Backup_Mod {
            get {
                return ResourceManager.GetString("Menu_Penumbra_Backup_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redraw all ähnelt.
        /// </summary>
        public static string Menu_Penumbra_Redraw_All {
            get {
                return ResourceManager.GetString("Menu_Penumbra_Redraw_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redraw self ähnelt.
        /// </summary>
        public static string Menu_Penumbra_Redraw_Self {
            get {
                return ResourceManager.GetString("Menu_Penumbra_Redraw_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Cache ähnelt.
        /// </summary>
        public static string Menu_Settings_Cache {
            get {
                return ResourceManager.GetString("Menu_Settings_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check preview pics in DB ähnelt.
        /// </summary>
        public static string Menu_Settings_CheckPreviews {
            get {
                return ResourceManager.GetString("Menu_Settings_CheckPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Mod Archive Path ähnelt.
        /// </summary>
        public static string Menu_Settings_ModPath {
            get {
                return ResourceManager.GetString("Menu_Settings_ModPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set PenumbraModPath ähnelt.
        /// </summary>
        public static string Menu_Settings_PenumbraPath {
            get {
                return ResourceManager.GetString("Menu_Settings_PenumbraPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rebuild db ähnelt.
        /// </summary>
        public static string Menu_Settings_RebuildDB {
            get {
                return ResourceManager.GetString("Menu_Settings_RebuildDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set TexTools Path ähnelt.
        /// </summary>
        public static string Menu_Settings_TexToolsPath {
            get {
                return ResourceManager.GetString("Menu_Settings_TexToolsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export as Json ähnelt.
        /// </summary>
        public static string Metadata_Export_Json {
            get {
                return ResourceManager.GetString("Metadata_Export_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find Mod in Penumbra ähnelt.
        /// </summary>
        public static string Metadata_FindInPenumbra {
            get {
                return ResourceManager.GetString("Metadata_FindInPenumbra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod-Name in penumbra ähnelt.
        /// </summary>
        public static string Metadata_PenumbraName {
            get {
                return ResourceManager.GetString("Metadata_PenumbraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Penumbra Mod-Path ähnelt.
        /// </summary>
        public static string Metadata_PenumbraPath {
            get {
                return ResourceManager.GetString("Metadata_PenumbraPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try Read from Mod ähnelt.
        /// </summary>
        public static string Metadata_ReadAffect {
            get {
                return ResourceManager.GetString("Metadata_ReadAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reread from archive ähnelt.
        /// </summary>
        public static string Metadata_Reread {
            get {
                return ResourceManager.GetString("Metadata_Reread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Same hash found, update found mod-data? ähnelt.
        /// </summary>
        public static string Metadata_SameHashFound {
            get {
                return ResourceManager.GetString("Metadata_SameHashFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chaching isn&apos;t enabled ähnelt.
        /// </summary>
        public static string Misc_Cache_Disabled {
            get {
                return ResourceManager.GetString("Misc_Cache_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install penumbra backup file ähnelt.
        /// </summary>
        public static string Misc_Install_Backup {
            get {
                return ResourceManager.GetString("Misc_Install_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete folder? ähnelt.
        /// </summary>
        public static string Msg_Delete_Folder_Confirm {
            get {
                return ResourceManager.GetString("Msg_Delete_Folder_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while fetching data. ähnelt.
        /// </summary>
        public static string Msg_Error_Fetch {
            get {
                return ResourceManager.GetString("Msg_Error_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished compressing. ähnelt.
        /// </summary>
        public static string Msg_Finished_Compressing {
            get {
                return ResourceManager.GetString("Msg_Finished_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No output direcory selected, aborting! ähnelt.
        /// </summary>
        public static string Msg_No_Output_Dir {
            get {
                return ResourceManager.GetString("Msg_No_Output_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No preview picture selected ähnelt.
        /// </summary>
        public static string Msg_No_Pic_Selected {
            get {
                return ResourceManager.GetString("Msg_No_Pic_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Looks like the wrong directory. Really want to continue? ähnelt.
        /// </summary>
        public static string Msg_Wrong_ModDir {
            get {
                return ResourceManager.GetString("Msg_Wrong_ModDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Animation ähnelt.
        /// </summary>
        public static string Type_Animation {
            get {
                return ResourceManager.GetString("Type_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Face ähnelt.
        /// </summary>
        public static string Type_Face {
            get {
                return ResourceManager.GetString("Type_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hair ähnelt.
        /// </summary>
        public static string Type_Hair {
            get {
                return ResourceManager.GetString("Type_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Housing ähnelt.
        /// </summary>
        public static string Type_Housing {
            get {
                return ResourceManager.GetString("Type_Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minion ähnelt.
        /// </summary>
        public static string Type_Minion {
            get {
                return ResourceManager.GetString("Type_Minion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mount ähnelt.
        /// </summary>
        public static string Type_Mount {
            get {
                return ResourceManager.GetString("Type_Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other mod ähnelt.
        /// </summary>
        public static string Type_Other {
            get {
                return ResourceManager.GetString("Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skin / Scales ähnelt.
        /// </summary>
        public static string Type_Skin {
            get {
                return ResourceManager.GetString("Type_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VFX ähnelt.
        /// </summary>
        public static string Type_Vfx {
            get {
                return ResourceManager.GetString("Type_Vfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod is an accessory ähnelt.
        /// </summary>
        public static string Types_Accessory {
            get {
                return ResourceManager.GetString("Types_Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        public static string Types_Bottom {
            get {
                return ResourceManager.GetString("Types_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays: ähnelt.
        /// </summary>
        public static string Types_Displays {
            get {
                return ResourceManager.GetString("Types_Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ear ähnelt.
        /// </summary>
        public static string Types_Ear {
            get {
                return ResourceManager.GetString("Types_Ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ring ähnelt.
        /// </summary>
        public static string Types_Finger {
            get {
                return ResourceManager.GetString("Types_Finger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hands ähnelt.
        /// </summary>
        public static string Types_Hands {
            get {
                return ResourceManager.GetString("Types_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head ähnelt.
        /// </summary>
        public static string Types_Head {
            get {
                return ResourceManager.GetString("Types_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neck ähnelt.
        /// </summary>
        public static string Types_Neck {
            get {
                return ResourceManager.GetString("Types_Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shoe ähnelt.
        /// </summary>
        public static string Types_Shoe {
            get {
                return ResourceManager.GetString("Types_Shoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string Types_Top {
            get {
                return ResourceManager.GetString("Types_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon ähnelt.
        /// </summary>
        public static string Types_Weapon {
            get {
                return ResourceManager.GetString("Types_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrist ähnelt.
        /// </summary>
        public static string Types_Wrist {
            get {
                return ResourceManager.GetString("Types_Wrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Word_Description {
            get {
                return ResourceManager.GetString("Word_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Word_Error {
            get {
                return ResourceManager.GetString("Word_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished ähnelt.
        /// </summary>
        public static string Word_Finished {
            get {
                return ResourceManager.GetString("Word_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string Word_Okay {
            get {
                return ResourceManager.GetString("Word_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pictures ähnelt.
        /// </summary>
        public static string Word_Pictures {
            get {
                return ResourceManager.GetString("Word_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replaces: ähnelt.
        /// </summary>
        public static string Word_Replaces {
            get {
                return ResourceManager.GetString("Word_Replaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Word_Save {
            get {
                return ResourceManager.GetString("Word_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types ähnelt.
        /// </summary>
        public static string Word_Types {
            get {
                return ResourceManager.GetString("Word_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Word_Warning {
            get {
                return ResourceManager.GetString("Word_Warning", resourceCulture);
            }
        }
    }
}
